package com.zpark.mapper;

import com.zpark.pojo.Tbbrand;
import java.util.List;

public interface TbbrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbrand
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbrand
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    int insert(Tbbrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbrand
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    Tbbrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbrand
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    List<Tbbrand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbrand
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    int updateByPrimaryKey(Tbbrand record);
}