package com.zpark.mapper;

import com.zpark.pojo.OrderVO;
import com.zpark.pojo.Tborder;
import java.util.List;

public interface TborderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborder
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborder
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    int insert(Tborder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborder
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    Tborder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborder
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    List<Tborder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborder
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    int updateByPrimaryKey(Tborder record);
    
    public List<OrderVO> selectAllOrderByPage(Tborder tborder);
}