package com.zpark.mapper;

import com.zpark.pojo.OrderDetailedVO;
import com.zpark.pojo.Tborderdetailed;
import java.util.List;

public interface TborderdetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborderdetailed
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborderdetailed
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    int insert(Tborderdetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborderdetailed
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    Tborderdetailed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborderdetailed
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    List<Tborderdetailed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tborderdetailed
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    int updateByPrimaryKey(Tborderdetailed record);
    
    public List<OrderDetailedVO> selectOrderDetailedById(Integer id);
}