package com.zpark.mapper;

import com.zpark.pojo.ProductVO;
import com.zpark.pojo.Tbproduct;
import java.util.List;

public interface TbproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbproduct
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbproduct
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    int insert(Tbproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbproduct
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    Tbproduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbproduct
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    List<Tbproduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbproduct
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    int updateByPrimaryKey(Tbproduct record);
    
    public List<Tbproduct> findTbproductAndTbcatalog (Tbproduct tbproduct);
    
    public List<ProductVO> selectProductByColumns(ProductVO productVO);
}