package com.zpark.pojo;

public class Tbbrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbrand.id
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbrand.brandid
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbrand.brandname
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    private String brandname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbrand.id
     *
     * @return the value of tbbrand.id
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbrand.id
     *
     * @param id the value for tbbrand.id
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbrand.brandid
     *
     * @return the value of tbbrand.brandid
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbrand.brandid
     *
     * @param brandid the value for tbbrand.brandid
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbrand.brandname
     *
     * @return the value of tbbrand.brandname
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbrand.brandname
     *
     * @param brandname the value for tbbrand.brandname
     *
     * @mbg.generated Wed Jun 05 15:37:24 CST 2019
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

	@Override
	public String toString() {
		return "Tbbrand [id=" + id + ", brandid=" + brandid + ", brandname=" + brandname + "]";
	}
    
}