package com.zpark.pojo;

public class Tbcatalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.catalog
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String catalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.catalogdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String catalogdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer showflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer goodflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbcatalog.parentid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.id
     *
     * @return the value of tbcatalog.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.id
     *
     * @param id the value for tbcatalog.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.catalog
     *
     * @return the value of tbcatalog.catalog
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.catalog
     *
     * @param catalog the value for tbcatalog.catalog
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.catalogdesc
     *
     * @return the value of tbcatalog.catalogdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getCatalogdesc() {
        return catalogdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.catalogdesc
     *
     * @param catalogdesc the value for tbcatalog.catalogdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setCatalogdesc(String catalogdesc) {
        this.catalogdesc = catalogdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.showflag
     *
     * @return the value of tbcatalog.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getShowflag() {
        return showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.showflag
     *
     * @param showflag the value for tbcatalog.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setShowflag(Integer showflag) {
        this.showflag = showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.goodflag
     *
     * @return the value of tbcatalog.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getGoodflag() {
        return goodflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.goodflag
     *
     * @param goodflag the value for tbcatalog.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setGoodflag(Integer goodflag) {
        this.goodflag = goodflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.serialno
     *
     * @return the value of tbcatalog.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.serialno
     *
     * @param serialno the value for tbcatalog.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbcatalog.parentid
     *
     * @return the value of tbcatalog.parentid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbcatalog.parentid
     *
     * @param parentid the value for tbcatalog.parentid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

	@Override
	public String toString() {
		return "Tbcatalog [id=" + id + ", catalog=" + catalog + ", catalogdesc=" + catalogdesc + ", showflag="
				+ showflag + ", goodflag=" + goodflag + ", serialno=" + serialno + ", parentid=" + parentid + "]";
	}
    
}