package com.zpark.pojo;

public class Tborderdetailed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.id
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.productname
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.productsn
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private String productsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.transactionprice
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private Double transactionprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.amount
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.subtotal
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private Double subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.orderid
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborderdetailed.picpath
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    private String picpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.id
     *
     * @return the value of tborderdetailed.id
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.id
     *
     * @param id the value for tborderdetailed.id
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.productname
     *
     * @return the value of tborderdetailed.productname
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.productname
     *
     * @param productname the value for tborderdetailed.productname
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.productsn
     *
     * @return the value of tborderdetailed.productsn
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public String getProductsn() {
        return productsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.productsn
     *
     * @param productsn the value for tborderdetailed.productsn
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setProductsn(String productsn) {
        this.productsn = productsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.transactionprice
     *
     * @return the value of tborderdetailed.transactionprice
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public Double getTransactionprice() {
        return transactionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.transactionprice
     *
     * @param transactionprice the value for tborderdetailed.transactionprice
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setTransactionprice(Double transactionprice) {
        this.transactionprice = transactionprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.amount
     *
     * @return the value of tborderdetailed.amount
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.amount
     *
     * @param amount the value for tborderdetailed.amount
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.subtotal
     *
     * @return the value of tborderdetailed.subtotal
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.subtotal
     *
     * @param subtotal the value for tborderdetailed.subtotal
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.orderid
     *
     * @return the value of tborderdetailed.orderid
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.orderid
     *
     * @param orderid the value for tborderdetailed.orderid
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborderdetailed.picpath
     *
     * @return the value of tborderdetailed.picpath
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborderdetailed.picpath
     *
     * @param picpath the value for tborderdetailed.picpath
     *
     * @mbg.generated Tue Jun 25 16:48:42 CST 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath;
    }

	@Override
	public String toString() {
		return "Tborderdetailed [id=" + id + ", productname=" + productname + ", productsn=" + productsn
				+ ", transactionprice=" + transactionprice + ", amount=" + amount + ", subtotal=" + subtotal
				+ ", orderid=" + orderid + ", picpath=" + picpath + "]";
	}
    
}