package com.zpark.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Tborder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.id
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private Integer id;	// 订单id

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.submittime
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date submittime;	// 提交时间

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.userid
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private Integer userid;	// 用户的id

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.amount
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private Double amount;	// 订单金额

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.payment
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String payment; //支付方式

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.source
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String source;	// 订单来源

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.orderstatus
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private Integer orderstatus;	//订单状态

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.orderno
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String orderno;	// 订单编号 时间+几位随机数

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.receiver
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String receiver;	// 收货人

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.tel
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String tel;	// 联系电话

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tborder.receiverAddr
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    private String receiveraddr;	// 收货地址

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.id
     *
     * @return the value of tborder.id
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.id
     *
     * @param id the value for tborder.id
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.submittime
     *
     * @return the value of tborder.submittime
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.submittime
     *
     * @param submittime the value for tborder.submittime
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.userid
     *
     * @return the value of tborder.userid
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.userid
     *
     * @param userid the value for tborder.userid
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.amount
     *
     * @return the value of tborder.amount
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.amount
     *
     * @param amount the value for tborder.amount
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.payment
     *
     * @return the value of tborder.payment
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.payment
     *
     * @param payment the value for tborder.payment
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setPayment(String payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.source
     *
     * @return the value of tborder.source
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.source
     *
     * @param source the value for tborder.source
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.orderstatus
     *
     * @return the value of tborder.orderstatus
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.orderstatus
     *
     * @param orderstatus the value for tborder.orderstatus
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.orderno
     *
     * @return the value of tborder.orderno
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.orderno
     *
     * @param orderno the value for tborder.orderno
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.receiver
     *
     * @return the value of tborder.receiver
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.receiver
     *
     * @param receiver the value for tborder.receiver
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.tel
     *
     * @return the value of tborder.tel
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.tel
     *
     * @param tel the value for tborder.tel
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tborder.receiverAddr
     *
     * @return the value of tborder.receiverAddr
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public String getReceiveraddr() {
        return receiveraddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tborder.receiverAddr
     *
     * @param receiveraddr the value for tborder.receiverAddr
     *
     * @mbg.generated Tue Jun 25 17:26:11 CST 2019
     */
    public void setReceiveraddr(String receiveraddr) {
        this.receiveraddr = receiveraddr;
    }

	@Override
	public String toString() {
		return "Tborder [id=" + id + ", submittime=" + submittime + ", userid=" + userid + ", amount=" + amount
				+ ", payment=" + payment + ", source=" + source + ", orderstatus=" + orderstatus + ", orderno="
				+ orderno + ", receiver=" + receiver + ", tel=" + tel + ", receiveraddr=" + receiveraddr + "]";
	}
    
}