package com.zpark.pojo;

public class Tbproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.productname
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.productsn
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String productsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.catalogid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer catalogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.brandid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer brandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.price
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.saleamout
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer saleamout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.saleprice
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Float saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.weight
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Float weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.productdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String productdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.productmark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String productmark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.amount
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer showflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.payflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer payflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer goodflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.picpath
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbproduct.productremark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String productremark;
    
    private Tbcatalog tbcatalog;

    public Tbcatalog getTbcatalog() {
		return tbcatalog;
	}

	public void setTbcatalog(Tbcatalog tbcatalog) {
		this.tbcatalog = tbcatalog;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.id
     *
     * @return the value of tbproduct.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.id
     *
     * @param id the value for tbproduct.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.productname
     *
     * @return the value of tbproduct.productname
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.productname
     *
     * @param productname the value for tbproduct.productname
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.productsn
     *
     * @return the value of tbproduct.productsn
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getProductsn() {
        return productsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.productsn
     *
     * @param productsn the value for tbproduct.productsn
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setProductsn(String productsn) {
        this.productsn = productsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.catalogid
     *
     * @return the value of tbproduct.catalogid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.catalogid
     *
     * @param catalogid the value for tbproduct.catalogid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.brandid
     *
     * @return the value of tbproduct.brandid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.brandid
     *
     * @param brandid the value for tbproduct.brandid
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setBrandid(Integer brandid) {
        this.brandid = brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.price
     *
     * @return the value of tbproduct.price
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.price
     *
     * @param price the value for tbproduct.price
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.saleamout
     *
     * @return the value of tbproduct.saleamout
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getSaleamout() {
        return saleamout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.saleamout
     *
     * @param saleamout the value for tbproduct.saleamout
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setSaleamout(Integer saleamout) {
        this.saleamout = saleamout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.saleprice
     *
     * @return the value of tbproduct.saleprice
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Float getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.saleprice
     *
     * @param saleprice the value for tbproduct.saleprice
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setSaleprice(Float saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.serialno
     *
     * @return the value of tbproduct.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.serialno
     *
     * @param serialno the value for tbproduct.serialno
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.weight
     *
     * @return the value of tbproduct.weight
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.weight
     *
     * @param weight the value for tbproduct.weight
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.productdesc
     *
     * @return the value of tbproduct.productdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getProductdesc() {
        return productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.productdesc
     *
     * @param productdesc the value for tbproduct.productdesc
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setProductdesc(String productdesc) {
        this.productdesc = productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.productmark
     *
     * @return the value of tbproduct.productmark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getProductmark() {
        return productmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.productmark
     *
     * @param productmark the value for tbproduct.productmark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setProductmark(String productmark) {
        this.productmark = productmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.amount
     *
     * @return the value of tbproduct.amount
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.amount
     *
     * @param amount the value for tbproduct.amount
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.showflag
     *
     * @return the value of tbproduct.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getShowflag() {
        return showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.showflag
     *
     * @param showflag the value for tbproduct.showflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setShowflag(Integer showflag) {
        this.showflag = showflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.payflag
     *
     * @return the value of tbproduct.payflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getPayflag() {
        return payflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.payflag
     *
     * @param payflag the value for tbproduct.payflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setPayflag(Integer payflag) {
        this.payflag = payflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.goodflag
     *
     * @return the value of tbproduct.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getGoodflag() {
        return goodflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.goodflag
     *
     * @param goodflag the value for tbproduct.goodflag
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setGoodflag(Integer goodflag) {
        this.goodflag = goodflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.picpath
     *
     * @return the value of tbproduct.picpath
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.picpath
     *
     * @param picpath the value for tbproduct.picpath
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbproduct.productremark
     *
     * @return the value of tbproduct.productremark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getProductremark() {
        return productremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbproduct.productremark
     *
     * @param productremark the value for tbproduct.productremark
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setProductremark(String productremark) {
        this.productremark = productremark;
    }

	@Override
	public String toString() {
		return "Tbproduct [id=" + id + ", productname=" + productname + ", productsn=" + productsn + ", catalogid="
				+ catalogid + ", brandid=" + brandid + ", price=" + price + ", saleamout=" + saleamout + ", saleprice="
				+ saleprice + ", serialno=" + serialno + ", weight=" + weight + ", productdesc=" + productdesc
				+ ", productmark=" + productmark + ", amount=" + amount + ", showflag=" + showflag + ", payflag="
				+ payflag + ", goodflag=" + goodflag + ", picpath=" + picpath + ", productremark=" + productremark
				+ ", tbcatalog=" + tbcatalog + "]";
	}
    
}