package com.zpark.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Tbuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.username
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.userpwd
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.email
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.createdate
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.userstatus
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    private Integer userstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.id
     *
     * @return the value of tbuser.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.id
     *
     * @param id the value for tbuser.id
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.username
     *
     * @return the value of tbuser.username
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.username
     *
     * @param username the value for tbuser.username
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.userpwd
     *
     * @return the value of tbuser.userpwd
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.userpwd
     *
     * @param userpwd the value for tbuser.userpwd
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.email
     *
     * @return the value of tbuser.email
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.email
     *
     * @param email the value for tbuser.email
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.createdate
     *
     * @return the value of tbuser.createdate
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.createdate
     *
     * @param createdate the value for tbuser.createdate
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.userstatus
     *
     * @return the value of tbuser.userstatus
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.userstatus
     *
     * @param userstatus the value for tbuser.userstatus
     *
     * @mbg.generated Wed May 08 10:45:33 CST 2019
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

	@Override
	public String toString() {
		return "Tbuser [id=" + id + ", username=" + username + ", userpwd=" + userpwd + ", email=" + email
				+ ", createdate=" + createdate + ", userstatus=" + userstatus + "]";
	}
    
}